-- keymaps from legendary.nvim (data/builtins.lua)
return {
    { mode = "n", lhs = "<C-o><C-o>", desc = "Reopen last opened file" },
    { mode = "n", lhs = "gx", desc = "Open with external app" },
    { mode = "n", lhs = "ZZ", desc = "Save and quit (window)" },
    { mode = "n", lhs = "ZQ", desc = "Quit without saving" },
    { mode = "n", lhs = "<Esc>", desc = "Back to normal mode" },
    { mode = "n", lhs = "<C-c>", desc = "Cancel command/operation" },
    { mode = "n", lhs = "i", desc = "Insert at cursor pos." },
    { mode = "n", lhs = "a", desc = "Append after cursor" },
    { mode = "n", lhs = "I", desc = "Insert at start of line" },
    { mode = "n", lhs = "A", desc = "Append at end of line" },
    { mode = "n", lhs = "o", desc = "Open new line below" },
    { mode = "n", lhs = "O", desc = "Open new line above" },
    { mode = "n", lhs = "r{c}", desc = "Replace character with {c}", incomplete = true },
    { mode = "n", lhs = "R", desc = "Replace mode/overwrite" },
    { mode = "n", lhs = "c", desc = "Change" },
    { mode = "n", lhs = "cc", desc = "Replace line" },
    { mode = "n", lhs = ".", desc = "Repeat last command" },
    { mode = "n", lhs = "u", desc = "Undo" },
    { mode = "n", lhs = "<C-r>", desc = "Redo" },
    { mode = "n", lhs = "g+", desc = "Next text state" },
    { mode = "n", lhs = "g-", desc = "Prev text state" },
    { mode = "n", lhs = "d", desc = "Cut" },
    { mode = "n", lhs = '"{r}d', desc = "Cut into register {r}", incomplete = true },
    { mode = "n", lhs = "dd", desc = "Cut line" },
    { mode = "n", lhs = "D", desc = "Cut until EOL" },
    { mode = "n", lhs = "x", desc = "Cut character under cursor" },
    { mode = "n", lhs = "X", desc = "Cut character left of cursor" },
    { mode = "n", lhs = "y", desc = "Copy" },
    { mode = "n", lhs = '"{r}y', desc = "Copy into register {r}", incomplete = true },
    { mode = "n", lhs = '"*y', desc = 'Copy into OS clipboard' },
    { mode = "n", lhs = "yy", desc = "Copy current line" },
    { mode = "n", lhs = "y$", desc = "Copy until EOL" },
    { mode = "n", lhs = "p", desc = "Paste after cursor" },
    { mode = "n", lhs = "P", desc = "Paste before cursor" },
    { mode = "n", lhs = '"{r}p', desc = "Paste from register {r}", incomplete = true },
    { mode = "n", lhs = "<C-r>{r}", desc = "Paste from register {r}", incomplete = true },
    { mode = "n", lhs = '"*p', desc = "Paste from OS clipboard" },
    { mode = "n", lhs = "]p", desc = "Paste after and align" },
    { mode = "n", lhs = "]P", desc = "Paste before and align" },
    { mode = "n", lhs = "v", desc = "Visual mode (select)" },
    { mode = "n", lhs = "V", desc = "Linewise visual mode" },
    { mode = "n", lhs = "<C-v>", desc = "Block visual mode" },
    -- { mode = "n", lhs = "<C-v>{Move}I", desc = "Insert in selected lines" },
    -- { mode = "n", lhs = "<C-v>{Move}A", desc = "Append to selected lines" },
    -- { mode = "n", lhs = "<C-v>{Move}c", desc = "Change in selected lines" },
    -- { mode = "n", lhs = "<C-v>{Move}x", desc = "Delete in selected lines" },
    { mode = "n", lhs = "gv", desc = "Reselect visual" },
    { mode = "n", lhs = "ggVG", desc = "Select all" },
    { mode = "n", lhs = "<C-w>", desc = "Delete previous word" },
    { mode = "n", lhs = "<C-u>", desc = "Erase line before cursor" },
    { mode = "n", lhs = "q{r}", desc = "Record macro into register {r}", incomplete = true },
    { mode = "n", lhs = "q", desc = "Stop recording macro" },
    { mode = "n", lhs = "@{r}", desc = "Run recorded macro in register {r}", incomplete = true },
    { mode = "n", lhs = "@@", desc = "Repeat last macro" },
    { mode = "n", lhs = "@:", desc = "Repeat last Ex command" },

    { mode = "n", lhs = "gU", desc = "Change to uppercase" },
    { mode = "n", lhs = "gu", desc = "Change to lowercase" },
    { mode = "n", lhs = "gUU", desc = "Uppercase line" },
    { mode = "n", lhs = "guu", desc = "Lowercase line" },
    { mode = "n", lhs = "U", desc = "Change to uppercase" },
    { mode = "n", lhs = "u", desc = "Change to lowercase" },
    { mode = "n", lhs = "~", desc = "Toggle case" },
    { mode = "v", lhs = ">", desc = "Indent" },
    { mode = "v", lhs = "<", desc = "Unindent" },
    { mode = "n", lhs = "=", desc = "Reindent" },
    { mode = "n", lhs = ">>", desc = "Indent line" },
    { mode = "n", lhs = "<<", desc = "Unindent" },
    { mode = "n", lhs = "==", desc = "Reindent line" },
    { mode = "i", lhs = "<C-t>", desc = "Indent line (insert mode)" },
    { mode = "i", lhs = "<C-d>", desc = "Unindent line (insert mode)" },
    { mode = "n", lhs = "gq", desc = "Hard-wrap (cursor moves)" },
    { mode = "n", lhs = "gw", desc = "Hard-wrap (cursor stays)" },
    { mode = "n", lhs = "gww", desc = "Format current line" },
    { mode = "n", lhs = "J", desc = "Join with next line" },
    { mode = "n", lhs = "gJ", desc = "Join next line preserve spaces" },
    { mode = "n", lhs = "<C-n>", desc = "Autocomplete (search forward)" },
    { mode = "n", lhs = "<C-p>", desc = "Autocomplete (search backwards)" },
    { mode = "i", lhs = "<C-x><C-o>", desc = "Omnicomplete" },
    { mode = "i", lhs = "<C-x><C-l>", desc = "Line autocomplete" },
    { mode = "i", lhs = "<C-k>{c}{c}", desc = "Insert digraph", incomplete = true },
    { mode = "i", lhs = "<C-r>=", desc = "Insert calculated expression" },
    { mode = "n", lhs = "<C-a>", desc = "Increment number" },
    { mode = "n", lhs = "<C-x>", desc = "Decrement number" },

    { mode = "n", lhs = "]s", desc = "To next misspelled word" },
    { mode = "n", lhs = "[s", desc = "To prev misspelled word" },
    { mode = "n", lhs = "z=", desc = "Suggest corrections (normal mode)" },
    { mode = "i", lhs = "<C-x>s", desc = "Suggest corrections (insert mode)" },
    { mode = "n", lhs = "zg", desc = "Permanently mark as correct" },
    { mode = "n", lhs = "zug", desc = "Undo mark as correct" },
    { mode = "n", lhs = "zG", desc = "Temporarily mark as correct" },
    { mode = "n", lhs = "zw", desc = "Permanently mark as incorrect" },
    { mode = "n", lhs = "zuw", desc = "Undo mark as incorrect" },
    { mode = "n", lhs = "zW", desc = "Temporarily mark as incorrect" },

    { mode = "n", lhs = "<C-f>", desc = "Scroll down a page" },
    { mode = "n", lhs = "<C-b>", desc = "Scroll up a page" },
    { mode = "n", lhs = "<C-d>", desc = "Scroll down half a page" },
    { mode = "n", lhs = "<C-u>", desc = "Scroll up half a page" },
    { mode = "n", lhs = "<C-e>", desc = "Scroll down a bit" },
    { mode = "n", lhs = "<C-y>", desc = "Scroll up a bit" },
    { mode = "n", lhs = "zl", desc = "Scroll horizontally right" },
    { mode = "n", lhs = "zh", desc = "Scroll horizontally left" },
    { mode = "n", lhs = "zL", desc = "Scroll horizontally half a screen" },
    { mode = "n", lhs = "zH", desc = "Scroll horizontally half a screen" },
    { mode = "n", lhs = "zt", desc = "Scroll line to top" },
    { mode = "n", lhs = "zb", desc = "Scroll to bottom" },
    { mode = "n", lhs = "zz", desc = "Scroll to center" },
    { mode = "n", lhs = "zR", desc = "Unfold all" },

    { mode = "n", lhs = "<C-^>", desc = "Edit last edited file" },
    { mode = "n", lhs = "<C-g>", desc = "Get file info" },
    { mode = "n", lhs = "ga", desc = "Character info" },
    { mode = "n", lhs = "gf", desc = "Go to file under cursor" },
    { mode = "n", lhs = "g<C-g>", desc = "Line/word/char count" },
    { mode = "n", lhs = "g%", desc = "Cycle match groups (eg. if,else,end) " },
    { mode = "n", lhs = "/{P}", desc = "Search forward for {P}", incomplete = true },
    { mode = "n", lhs = "?{P}", desc = "Search backward for {P}", incomplete = true },
    { mode = "n", lhs = "n", desc = "Go to next match" },
    { mode = "n", lhs = "N", desc = "Go to previous match" },
    { mode = "n", lhs = 'gn', desc = "Select up to next match" },
    { mode = "n", lhs = "gN", desc = "Select up to prev match" },
    { mode = "n", lhs = "*", desc = "Search word under cursor backward" },
    { mode = "n", lhs = "#", desc = "Search word under cursor forward" },
    { mode = "n", lhs = "<C-G>", desc = "Go to next match during search" },
    { mode = "n", lhs = "<C-T>", desc = "Go to previous match during search" },
    { mode = "n", lhs = "<C-n>", desc = "Next command (command mode)" },
    { mode = "n", lhs = "<C-p>", desc = "Prev command (command mode)" },
    { mode = "n", lhs = "q:", desc = "Browse command history" },
    { mode = "n", lhs = "q/", desc = "Browse search patterns" },
    { mode = "n", lhs = "]c", desc = "Next difference" },
    { mode = "n", lhs = "[c", desc = "Prev difference" },
    { mode = "n", lhs = "dp", desc = "Diff put" },
    { mode = "n", lhs = "do", desc = "Diff obtain" },
    { mode = "n", lhs = "h", desc = "Left" },
    { mode = "n", lhs = "l", desc = "Right" },
    { mode = "n", lhs = "k", desc = "Up" },
    { mode = "n", lhs = "j", desc = "Down" },
    { mode = "n", lhs = "gk", desc = "Up (honor soft-wrapping)" },
    { mode = "n", lhs = "gj", desc = "Down (honor soft-wrapping)" },
    { mode = "n", lhs = "w", desc = "Start of next word" },
    { mode = "n", lhs = "b", desc = "Start of prev word" },
    { mode = "n", lhs = "e", desc = "End of next word" },
    { mode = "n", lhs = "ge", desc = "End of prev word" },
    { mode = "n", lhs = "W", desc = "Start of next WORD" },
    { mode = "n", lhs = "B", desc = "Start of prev WORD" },
    { mode = "n", lhs = "E", desc = "End of next WORD" },
    { mode = "n", lhs = "gE", desc = "End of prev WORD" },
    { mode = "n", lhs = "0", desc = "Start of line" },
    { mode = "n", lhs = "$", desc = "End of line" },
    { mode = "n", lhs = "^", desc = "This line 1st non-blank" },
    { mode = "n", lhs = "+", desc = "Next line 1st non-blank" },
    { mode = "n", lhs = "-", desc = "Prev line 1st non-blank" },
    { mode = "n", lhs = "gg", desc = "First line" },
    { mode = "n", lhs = "G", desc = "Last line" },
    { mode = "n", lhs = "f{c}", desc = "Next {c} in this line", incomplete = true },
    { mode = "n", lhs = "t{c}", desc = "Just before next {c}", incomplete = true },
    { mode = "n", lhs = "F{c}", desc = "Prev {c} in this line", incomplete = true },
    { mode = "n", lhs = "T{c}", desc = "Just after prev {c}", incomplete = true },
    { mode = "n", lhs = ";", desc = "Repeat f/t/F/T forward" },
    { mode = "n", lhs = ",", desc = "Repeat f/t/F/T backward" },
    { mode = "n", lhs = "g;", desc = "Prev pos in change list" },
    { mode = "n", lhs = "g,", desc = "Next pos in change list" },
    { mode = "n", lhs = "{n}|", desc = "Go to column {n}", incomplete = true },
    { mode = "n", lhs = "{n}G", desc = "Jump to line {n}", incomplete = true },
    { mode = "n", lhs = "}", desc = "Jump to next blank line" },
    { mode = "n", lhs = "{", desc = "Jump to prev blank line" },
    { mode = "n", lhs = "[{", desc = "Jump to begin of block" },
    { mode = "n", lhs = "]}", desc = "Jump to end of block" },
    { mode = "n", lhs = ")", desc = "Jump to end of sentence" },
    { mode = "n", lhs = "(", desc = "Jump to beg. of sentence" },
    { mode = "n", lhs = "]]", desc = "Jump to end of section" },
    { mode = "n", lhs = "[[", desc = "Jump to beg. of section" },
    { mode = "n", lhs = "H", desc = "Jump to top of window" },
    { mode = "n", lhs = "M", desc = "Jump to middle" },
    { mode = "n", lhs = "L", desc = "Jump to bottom" },
    { mode = "n", lhs = "%", desc = "Jump to matching delim" },
    { mode = "n", lhs = "<C-t>", desc = "Jump to older tag" },
    { mode = "n", lhs = "<C-]>", desc = "Jump to tag definition" },
    { mode = "n", lhs = "g]", desc = "Jump to tag definition, show choices " },
    { mode = "n", lhs = "g<C-]>", desc = "Jump or show choices" },
    { mode = "n", lhs = "m{c}", desc = "Set mark {c}", incomplete = true },
    { mode = "n", lhs = "`{c}", desc = "Jump to mark at {c}", incomplete = true },
    { mode = "n", lhs = "<C-o>", desc = "To prev jump position" },
    { mode = "n", lhs = "<C-i>", desc = "To next jump position" },
    { mode = "n", lhs = "gi", desc = "Go to last insertion and INSERT" },

    { mode = "n", lhs = "zj", desc = "Go to start of next fold" },
    { mode = "n", lhs = "zk", desc = "Go to end of previous fold" },
    { mode = "n", lhs = "zo", desc = "Open fold under cursor" },
    { mode = "n", lhs = "zO", desc = "Open all folds under cursor" },
    { mode = "n", lhs = "zc", desc = "Close fold under cursor" },
    { mode = "n", lhs = "zC", desc = "Close all folds under cursor" },
    { mode = "n", lhs = "za", desc = "Toggle fold under cursor" },
    { mode = "n", lhs = "zA", desc = "Toggle all folds under cursor" },
    { mode = "n", lhs = "zv", desc = "Open folds to show cursor line" },
    { mode = "n", lhs = "zM", desc = "Close all folds" },
    { mode = "n", lhs = "zR", desc = "Open all folds" },
    { mode = "n", lhs = "zm", desc = "Fold more" },
    { mode = "n", lhs = "zr", desc = "Fold less" },
    { mode = "n", lhs = "zx", desc = "Update folds" },
    { mode = "n", lhs = "<C-w><C-n>", desc = "New horizontal split" },
    { mode = "n", lhs = "<C-w>c", desc = "Close window" },
    { mode = "n", lhs = "<C-w><C-o>", desc = "Close inactive windows" },
    { mode = "n", lhs = "<C-w>s", desc = "Split horizontally" },
    { mode = "n", lhs = "<C-w><C-v>", desc = "Split vertically" },
    { mode = "n", lhs = "<C-w><C-x>", desc = "Exchange windows" },
    { mode = "n", lhs = "<C-w>K", desc = "Move to the very top" },
    { mode = "n", lhs = "<C-w>J", desc = "Move to the very bottom" },
    { mode = "n", lhs = "<C-w>L", desc = "Move to the far right" },
    { mode = "n", lhs = "<C-w>H", desc = "Move to the far left" },
    { mode = "n", lhs = "<C-w><C-w>", desc = "Cycle through windows" },
    { mode = "n", lhs = "<C-w><C-p>", desc = "Back to previous window" },
    { mode = "n", lhs = "<C-w><C-h>", desc = "Edit window to the left" },
    { mode = "n", lhs = "<C-w><C-j>", desc = "Edit window below" },
    { mode = "n", lhs = "<C-w><C-k>", desc = "Edit window above" },
    { mode = "n", lhs = "<C-w><C-l>", desc = "Edit window to the right" },
    { mode = "n", lhs = "<C-w><C-t>", desc = "Edit top window" },
    { mode = "n", lhs = "<C-w><C-b>", desc = "Edit bottom window" },
    { mode = "n", lhs = "<C-w>=", desc = "All windows same size" },
    { mode = "n", lhs = "<C-w>_", desc = "Maximize height" },
    { mode = "n", lhs = "<C-w>|", desc = "Maximize width" },
    { mode = "n", lhs = "<C-w>-", desc = "Decrease height" },
    { mode = "n", lhs = "<C-w>+", desc = "Increase height" },
    { mode = "n", lhs = "<C-w><", desc = "Decrease width" },
    { mode = "n", lhs = "<C-w>>", desc = "Increase width" },
    { mode = "n", lhs = "gt", desc = "Next tab" },
    { mode = "n", lhs = "gT", desc = "Previous tab" },
    { mode = "n", lhs = "{n}gt", desc = "Go to tab {n}", incomplete = true },
    { mode = "n", lhs = "<C-w>T", desc = "Move window to new tab" },
    -- { mode = "n", lhs = "%:p", desc = "Full path" },
    -- { mode = "n", lhs = "%:~", desc = "Relative to $HOME" },
    -- { mode = "n", lhs = "%:.", desc = "Relative to current directory" },
    -- { mode = "n", lhs = "%:t", desc = "Filename only (tail)" },
    -- { mode = "n", lhs = "%:r", desc = "Remove last extension (get root)" },
    -- { mode = "n", lhs = "%:e", desc = "Extension only" },
    -- { mode = "n", lhs = "%:S", desc = "Escape special chars (use in shell)" },
    -- { mode = "n", lhs = "%:s?pat?sub?", desc = "Substitute first" },
    -- { mode = "n", lhs = "%:gs?pat?sub?", desc = "Substitute all" },
    -- { mode = "n", lhs = "%:p:h", desc = "Get directory of file" },
}
